drop policy if exists institution_documents_write on public.institution_documents;
create policy institution_documents_insert on public.institution_documents for insert to authenticated with check ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));
create policy institution_documents_update on public.institution_documents for update to authenticated using ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text])))) with check ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));
create policy institution_documents_delete on public.institution_documents for delete to authenticated using ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));

drop policy if exists institution_rules_write on public.institution_rule_versions;
create policy institution_rules_insert on public.institution_rule_versions for insert to authenticated with check ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));
create policy institution_rules_update on public.institution_rule_versions for update to authenticated using ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text])))) with check ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));
create policy institution_rules_delete on public.institution_rule_versions for delete to authenticated using ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));

drop policy if exists institution_settings_write on public.institution_settings;
create policy institution_settings_insert on public.institution_settings for insert to authenticated with check ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));
create policy institution_settings_update on public.institution_settings for update to authenticated using ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text])))) with check ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));
create policy institution_settings_delete on public.institution_settings for delete to authenticated using ((current_app_role() = 'superadmin'::text) OR ((tenant_id = current_tenant_id()) AND (current_app_role() = ANY (ARRAY['admin'::text, 'direccion'::text]))));
